[build]
  builder = "Nixpacks"

[[services]]
name = "backend"
build_command = "cd backend && go build -ldflags '-s -w' -o server server.go"
start_command = "./backend/server"

[[services]]
name = "frontend"
build_command = "cd frontend && npm install && npm run build"
start_command = "cd frontend && npm run preview"